name: Robin Vincent
favicon: null
layout_spectrum: 0.5216702967882156
typography_spectrum: 0.48993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#250000'
    - '#f6b41f'
    - '#c14600'
    - '#e06e0e'
    - '#991e00'
  brandStrength: 0.5
  lightness: 0.06585986283607781
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
